### ISSUE TITLE
Issue while fetching Organization, User and Members in v11

### ISSUE THREAD

**Issue by st-aprajapati** [OCA/interface-git#14]
Getting below error while syncing data from github in v11(Setting --> Sync Object --> Load From Github).

![error_log](https://user-images.githubusercontent.com/40430352/41660415-95fcd57a-74b9-11e8-9feb-ffd681c73698.png)

**Comment by pedrobaeza** [comment]
Which organization?

**Comment by gdgellatly** [comment]
@st-aprajapati Where is the PR as I understand this has been fixed by you already?

@cubells @pedrobaeza This is Surekha Tech working on the v11 github oca RFQ.  I think the organization is just a demo fork of a few OCA repos but not 100% sure.

**Comment by pedrobaeza** [comment]
OK, I have assigned my colleague who migrated this to check

**Comment by st-aprajapati** [comment]
@gdgellatly : I have fixed this and created PR for the same. Here is my PR 
https://github.com/OCA/interface-github/pull/15

@cubells & @pedrobaeza : Please review it when you get a chance.

**Comment by pedrobaeza** [comment]
Merged, so I close.

**Comment by cubells** [comment]
thanks @st-aprajapati  you are fast!
