### ISSUE TITLE
create inside computed fields causes deep recursion

### ISSUE THREAD

**Issue by sbidoul** [OCA/interface-git#5]
The method that computes dependent module lists itself creates module objects.

https://github.com/OCA/interface-github/blob/8ac5340879babefe8791674378eadb0231fcc0a1/github_connector_odoo/models/odoo_module_version.py#L216-L224

This causes deep recursion with Odoo repeatedly attempting to recompute the dependency after each module creation. I had to increase the python recursion limit to 2000 to have https://github.com/OCA/l10n-peru/blob/8.0/opl_all/__openerp__.py load correctly in interface-github.

**Comment by legalsylvain** [comment]
Hi.

well I saw that problem. (for that reason, in the demo data, there was l10n-peru.
https://github.com/OCA/interface-github/blob/11.0/github_connector/demo/github_organization.xml#L24

Well I think that the problem maybe come from the module. don't you think ?
I opened an issue 2 years ago but I had no answer.

https://github.com/OCA/l10n-peru/issues/4

I see removing this module from the repository as a more simple solution.
