### ISSUE TITLE
Repository branch -> Modules smart button broken

### ISSUE THREAD

**Issue by sbidoul** [OCA/interface-git#67]
When clicking on the modules button, we land on the wrong branch / repo.

![image](https://user-images.githubusercontent.com/692075/96364486-354e5200-113b-11eb-9cc0-b602e25c30ec.png)

![image](https://user-images.githubusercontent.com/692075/96364531-57e06b00-113b-11eb-8423-b27f48bb4d93.png)

**Comment by pedrobaeza** [comment]
Yes, this is a known problem that is solved in 13.0 branch in 92240be1f172ee79c808bdab8e10ba7b532b35a4. It's due to the handling of `active_id` in Odoo itself.
